### ISSUE TITLE
Add Description

### ISSUE THREAD

**Issue by prince-chrismc** [g-harel/SOEN423P#2]
**Is your feature request related to a problem? Please describe.**
I can not add a description since I am not the owner and it's currently blank so someone like @g-harel might be able to help

**Describe the solution you'd like**
add the following
> This is a Java repository to contain our group project for Distributed Systems (SOEN423) from Concordia University during Fall 2018.

**Describe alternatives you've considered**
I was unable to do it myself. So here I am...

**Comment by g-harel** [comment]
![image](https://user-images.githubusercontent.com/9319710/48450112-01aa6680-e773-11e8-9b37-f4280121c3ef.png)
